### ISSUE TITLE
Redesign game ui

### ISSUE THREAD

**Issue by Were42** [mazanec202/rust-uno#87]
- [x] ruka hráče by měla zabírat celou šířku
- [x] přibude game logger s 4-5 zprávami pro lepší přehled tvar zprávy <player_name>:<action>
- [x] pointer na draw a cartu

**TODOS**
- [x] Vystředit karty v ruce hráče na tahu
- [x] V loggeru vypsat kartu, která byla zahrána
- [x] V loggeru použávat slider
- [ ] V loggeru uvést čas akce
- [x] Do loggeru přidat reakci na DRAW ME wsmsg
- [x] Do loggeru zaznamenat, že byl hráč přeskočen (dostal 0 karet)
